config/routes.rb
Twitter::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :posts

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :message
	validates_length_of :message, :maximum => 140, :allow_blank => false
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
  
  def find_by_username(login)
    return find_by_username(login)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index  
	@posts = Post.all(:order => "created_at DESC")
    respond_to do |format|  
      format.html  
    end  
  end  
  
  def create  
    @post = Post.create(:message => params[:message], :user_id => current_user.id)  
    respond_to do |format|  
      if @post.save  
        format.json { render :json => @post, :include => { :user => { :only => [:username] } } }
      else  
        flash[:notice] = "Message failed to save."
		format.jsonr do
		render :status => 400, :json => {
		:status => :error,
		
		:html => ""
		}.to_json
		end 
      end  
    end  
  end
  
  def show  
	@id_user = User.find_by_username(params[:id])
	@posts = Post.all(:conditions => { :user_id => @id_user }, :order => "created_at DESC")
	@username = @posts.first().user.username
    respond_to do |format|  
      format.html  
    end  
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">  
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">  
<head>  
      <b><%= stylesheet_link_tag 'layout' %></b>
</head>  
<body>  
	<div id="content">  
    <p><%= render :partial => "users/login" %></p>  
  
    <%= yield %>  
  </div>
</body>  
</html>  

app/views/posts/_message_form.html.erb
<% if logged_in? %>  
	<%= form_tag(:controller => "posts", :action => "create") do %>  
	  <%= label_tag(:message, "What are you doing?") %><br />  
	  <%= text_area_tag(:message, nil, :size => "44x6", :id => "txt_message") %><br />  
	  <%= submit_tag("Post", :id => "submit_message") %>  
	<% end %>
<% end %>

app/views/posts/_post.html.erb
    <p><b>Posted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.user.username, posts_path + '/' + post.user.username %></b></p>  
    <p>
		<%= post.message %>
	</p>  
			

app/views/posts/index.html.erb
    <% title "Looks like tweets" %>

	<% if logged_in? %>
	<div id="errors"></div>
	<b><%= render :partial => "message_form" %></b>  
	<% end %>

	<div style="height: 60px">
	<div id="realtime_count"></div>
	</div>

	<div id="realtime_unread_tweets">

	</div>
    <%= render :partial => @posts %>
	<script type="text/javascript" src="http://localhost:1188/socket.io/socket.io.js"></script>
	<%= javascript_include_tag :jquery %>
	<%= javascript_include_tag :timeago %>
	<%= javascript_include_tag :realtime_post %>

app/views/posts/show.html.erb
<% title "Posts" %>

<h1><%= @username%>'s timeline</h1>
<%= render :partial => @posts %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/_login.html.erb
<% if logged_in? %>  
  Welcome <%= current_user.username %>! Not you?  
  <%= link_to "Log out", logout_path %>  
<% else %>  
  <%= link_to "Sign up", signup_path %> or  
  <%= link_to "log in", login_path %>.
<% end %> 

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>